# config.py
import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    # OpenAI Settings
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4-turbo-preview")
    EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-ada-002")
    TEMPERATURE = float(os.getenv("TEMPERATURE", 0.1))
    
    # Processing Settings
    CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", 1000))
    CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP", 200))
    TOP_K = int(os.getenv("TOP_K", 10))
    
    # Vector Store Settings
    VECTOR_STORE_TYPE = os.getenv("VECTOR_STORE_TYPE", "chroma")
    
    # Email Settings
    GMAIL_EMAIL = os.getenv("GMAIL_EMAIL", "nivasrini620@gmail.com")
    GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")
    EMAIL_ENABLED = os.getenv("EMAIL_ENABLED", "false").lower() == "true"
    AUTO_SEND_RESULTS = os.getenv("AUTO_SEND_RESULTS", "false").lower() == "true"
    
    # Storage Paths
    DATA_DIR = "./data"
    CHROMA_PATH = f"{DATA_DIR}/chroma"
    FAISS_PATH = f"{DATA_DIR}/faiss"
    SYSTEM_OUTPUTS_PATH = f"{DATA_DIR}/system_outputs"
    
    # SAP Keywords
    SAP_KEYWORDS = [
        "system", "alert", "critical", "warning", "recommendation",
        "performance", "database", "memory", "cpu", "response time",
        "HANA", "ABAP", "client", "user", "job", "batch"
    ]

# Email Templates
EMAIL_TEMPLATES = {
    "search_results": {
        "subject": "SAP RAG Analysis Results - {query}",
        "body_template": """
SAP Early Watch Analyzer - Search Results
==========================================

Query: {query}
Timestamp: {timestamp}
Confidence: {confidence:.1f}%

EXECUTIVE SUMMARY:
{summary}

CRITICAL FINDINGS ({critical_count}):
{critical_findings}

RECOMMENDATIONS ({rec_count}):
{recommendations}

---
Generated by SAP RAG System
"""
    }
}